# Generated by Django 2.2.8 on 2019-12-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Ad/Soyad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagesauthor/', verbose_name='Sekil')),
                ('gender', models.BooleanField(default=False, verbose_name='Cinsiyyet')),
                ('date_of_birthday', models.DateField(auto_now=True, verbose_name='Doguldugu tarix')),
                ('nationality', models.CharField(max_length=255, verbose_name='Milliyet')),
                ('info', models.TextField(default='Yaxsi dram kitablari yazir', verbose_name='Melumat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Muellif',
                'verbose_name_plural': 'Muellifler',
                'ordering': ('fullname',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ad')),
                ('description', models.TextField(default='Recommended Book', verbose_name='Melumat')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Qiymet')),
                ('pagecount', models.IntegerField(verbose_name='Sehife sayi')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Uz qabigi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Author')),
            ],
            options={
                'verbose_name': 'Kitab',
                'verbose_name_plural': 'Kitablar',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Basliq')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rel', models.ManyToManyField(to='bookapp.Book')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ('title',),
            },
        ),
    ]
