# Generated by Django 2.2.8 on 2019-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='rel',
        ),
        migrations.AddField(
            model_name='book',
            name='book_categoy',
            field=models.ManyToManyField(to='bookapp.Category'),
        ),
    ]
