# Generated by Django 2.2.8 on 2019-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20191220_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_categoy',
            new_name='book_category',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birthday',
            field=models.DateField(verbose_name='Doguldugu tarix'),
        ),
    ]
